### ISSUE TITLE
How to refresh token with this package?

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [xinranxiao/meteor-spotify#5]
Hi, I'm finding this package very useful - thank you for sharing it!

After looking awhile for a way to refresh the token in a manner similar to the nifty method you've implemented [here](https://github.com/xinranxiao/meteor-spotify-web-api/blob/master/spotify-api.js#L12) but I haven't found a similarly straightforward way to do it.

Am I missing something? My apologies if so, this is my first time experimenting with meteor...

Thanks!

AKA

**Comment by xinranxiao** [comment]
Hey, thanks for using the package.

This was really meant to be used along-side with the accounts-spotify package... if you wanted to refresh it manually you would have to make direct calls to spotify's auth service. I'd avoid that and just use accounts-spotify to login with Spotify, or even https://github.com/xinranxiao/meteor-spotify-web-api if you wanted to make API calls

**Comment by AKAMEDIASYSTEM** [comment]
Thank you for your reply! I actually _am_ using accounts-spotify, and I can't figure out how to refresh the token there either ;-)

This issue can be Closed, though, since it seems I've opened it in the wrong place (sorry!)

Thanks again for your help,

AKA
